name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests (if any)
        run: npm test --if-present
        continue-on-error: true
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ai-hypnosis
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          
      - name: Verify deployment
        run: |
          echo "Deployment complete!"
          echo "Check your Cloudflare Pages dashboard for the deployment URL"
          
      - name: Run post-deployment health check
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          sleep 30
          # The deployment URL will be available in Cloudflare dashboard
          # You can add a health check here once you have the stable URL